# Generated by Django 5.1.1 on 2024-09-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfield',
            options={'permissions': [('can_delete_own_post', 'Can delete own post'), ('can_delete_any_post', 'Can delete any post')]},
        ),
        migrations.AlterModelOptions(
            name='replyfield',
            options={'permissions': [('can_delete_own_reply', 'Can delete own reply'), ('can_delete_any_reply', 'Can delete any reply')]},
        ),
    ]
