# Generated by Django 5.1.1 on 2024-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_postfield_options_alter_replyfield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfield',
            options={},
        ),
        migrations.AlterModelOptions(
            name='replyfield',
            options={},
        ),
        migrations.AddField(
            model_name='userfield',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
