# Generated by Django 5.1.1 on 2024-09-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_postfield_options_alter_replyfield_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='role',
        ),
    ]
