# Generated by Django 5.1.1 on 2024-09-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_userfield_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfield',
            options={'permissions': []},
        ),
    ]
