# Generated by Django 5.1.1 on 2024-09-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_userfield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfield',
            options={'default_permissions': ()},
        ),
    ]
