# Generated by Django 5.1.1 on 2024-09-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_userfield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfield',
            options={'permissions': [('can_delete_post', 'Can delete post'), ('can_delete_any_post', 'Can delete any post')]},
        ),
        migrations.AlterModelOptions(
            name='replyfield',
            options={'permissions': [('can_delete_reply', 'Can delete reply'), ('can_delete_any_reply', 'Can delete any reply')]},
        ),
        migrations.AlterModelOptions(
            name='userfield',
            options={},
        ),
    ]
